Send message for members
dbm-network/extensions pull request #12
Opened 2020-03-21 23:32 UTC by DiogoG04

Members can also send a simple message
After clicking Run, you will see the name of the channel that the message was sent and the name of the server

2020-03-21 23:34 UTC, almeidx requested changes
The file has no extension.

2020-03-22 01:26 UTC, DiogoG04 commented
placed extension : )

2020-03-23 02:46 UTC, almeidx requested changes

2020-03-23 02:46 UTC, Almeeida commented on extensions/dbm_dashboard/dbm_dashboard_EXT/actions/actions/send_msg_members.js
> +    name: "Send Menssage for channel",
```suggestion
    name: "Send Message for channel",
```

2020-03-23 08:04 UTC, DiogoG04 commented on extensions/dbm_dashboard/dbm_dashboard_EXT/actions/actions/send_msg_members.js
> +    name: "Send Menssage for channel",
sorry 😕

2020-03-23 15:13 UTC, almeidx approved these changes

2020-03-23 15:13 UTC, merged